[package]
name = "rustyfim"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustyfim"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.4", features = ["extension-module"] }
bitvec = { version = "0.19.6", optional = true }
bitmatrix = { version = "0.1", optional = true }
rayon = "1.5.2"
itertools = "0.6.1"
argparse = "*"
fnv = "1.0.6"

[features]
default = ["bitmatrix", "bitvec"]

[profile.release]
debug = true
