[package]
name = "rustyfim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustyfim"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
rayon = "0.8.2"
itertools = "0.6.1"
argparse = "*"
fnv = "1.0.6"

[profile.release]
debug = true