name: continuous-integration

on:
  push:
    branches:
      - '@dezhi/neclatclosed'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "13.0"
    - run: llvm-config --version
    - uses: messense/maturin-action@v1
      with:
        manylinux: "2014"
        command: list-python
    - run: bash ./pgo.sh x86_64-unknown-linux-gnu
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  macos-aarch64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release -o dist -i python3.10 --features simd
        target: aarch64-apple-darwin
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  macos-amd64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release -o dist -i python3.10 --features simd
        target: x86_64-apple-darwin
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist
